#!/usr/bin/env python3
# Turn the `.btf_tags` manifest emitted by `#[btf_tag]` into the debug-info
# annotations the BPF backend reads, then delete the manifest.
#
# Usage: btf_tags.py input.ll output.ll
#
# `BTFDebug` derives BTF_KIND_DECL_TAG and BTF_KIND_TYPE_TAG from the
# `annotations:` field of a debug-info node:
#
#   !DIDerivedType(tag: DW_TAG_pointer_type, ..., annotations: !10)
#   !10 = !{!11}
#   !11 = !{!"btf_type_tag", !"kptr"}
#
# rustc cannot emit that field, so `#[btf_tag]` records the request as a
# NUL-terminated directive in a `#[used]` static in section ".btf_tags" (see
# btf-macros/src/tags.rs for the grammar) and this pass performs the edit.
#
# This is a textual pass rather than part of bpf-postproc for two reasons.
# DISubprogram drops trailing null operands, so a rustc-emitted one usually has
# no `annotations` operand slot at all and the LLVM C API cannot grow an
# MDNode. And BTF is generated by llc from debug info, so the last point before
# codegen -- here -- is where the annotations have to exist.

import re, sys

text = open(sys.argv[1]).read()


def die(msg):
    sys.stderr.write(f'btf_tags.py: {msg}\n')
    sys.exit(1)


# ---------------------------------------------------------------- manifest --

# The static keeps whatever linkage and mangled name rustc gave it; the section
# is the only reliable marker.
MANIFEST_RE = re.compile(
    r'^(@[^\s=]+) = [^\n]*?\[\d+ x i8\] c"((?:[^"\\]|\\.)*)"[^\n]*'
    r'section "\.btf_tags"[^\n]*$',
    re.MULTILINE)


def unescape(s):
    """Decode an LLVM c"..." string body."""
    out, i = bytearray(), 0
    while i < len(s):
        if s[i] == '\\' and i + 1 < len(s):
            if s[i + 1] == '\\':
                out.append(0x5C)
                i += 2
            else:
                out.append(int(s[i + 1:i + 3], 16))
                i += 3
        else:
            out.append(ord(s[i]))
            i += 1
    return bytes(out)


manifest_globals = []
directives = []
for m in MANIFEST_RE.finditer(text):
    manifest_globals.append(m.group(1))
    directive = unescape(m.group(2)).rstrip(b'\0').decode('utf-8', 'replace')
    if not directive:
        continue
    parts = directive.split('|')
    if len(parts) != 5:
        die(f'malformed directive {directive!r}')
    directives.append(tuple(parts))

if not directives and not manifest_globals:
    open(sys.argv[2], 'w').write(text)
    sys.exit(0)

# ------------------------------------------------------- metadata plumbing --

next_id = max((int(m[1:]) for m in re.findall(r'!\d+', text)), default=0) + 1
new_metadata = []


def alloc():
    global next_id
    node = f'!{next_id}'
    next_id += 1
    return node


def annotations_node(tags):
    """`!N` for a tuple of (kind, tag) pairs, in the order given.

    Order is load bearing for btf_type_tag: BTFDebug turns [tag1, tag2] into
    the chain PTR -> tag2 -> tag1 -> base, which is what clang produces for
    `int __tag1 __tag2 *p`.
    """
    entries = []
    for kind, tag in tags:
        node = alloc()
        name = 'btf_type_tag' if kind == 't' else 'btf_decl_tag'
        new_metadata.append(f'{node} = !{{!"{name}", !"{tag}"}}')
        entries.append(node)
    tuple_node = alloc()
    new_metadata.append(f'{tuple_node} = !{{{", ".join(entries)}}}')
    return tuple_node


def node_line(node):
    """The `!N = ...` definition line for a metadata id."""
    m = re.search(r'^' + re.escape(node) + r' = .*$', text, re.MULTILINE)
    return m.group(0) if m else None


def replace_node_line(node, new_line):
    global text
    text = re.sub(r'^' + re.escape(node) + r' = .*$',
                  lambda _: new_line, text, count=1, flags=re.MULTILINE)


def attach_annotations(node, tags, what):
    """Add `annotations: !N` to an existing metadata node."""
    line = node_line(node)
    if line is None:
        die(f'{what}: metadata node {node} disappeared')
    if 'annotations:' in line:
        die(f'{what}: {node} already carries annotations')
    if not line.endswith(')'):
        die(f'{what}: cannot parse {node}')
    replace_node_line(node, f'{line[:-1]}, annotations: {annotations_node(tags)})')


def tuple_elements(node):
    line = node_line(node)
    if line is None:
        return []
    m = re.match(r'^!\d+ = (?:distinct )?!\{(.*)\}$', line)
    if not m or not m.group(1).strip():
        return []
    return [e.strip() for e in m.group(1).split(',')]


# --------------------------------------------------------------- DI lookups --

def find_struct(name):
    # Self-referential structs (a `*mut Self` field) come out `distinct`.
    m = re.search(
        r'^(!\d+) = (?:distinct )?!DICompositeType\(tag: DW_TAG_structure_type, '
        r'name: "' + re.escape(name) + r'"[,)][^\n]*$',
        text, re.MULTILINE)
    if not m:
        die(f'no debug info for struct `{name}` '
            f'(is it the type of a #[used] static or a live local?)')
    return m.group(1)


def find_member(struct, field):
    struct_node = find_struct(struct)
    line = node_line(struct_node)
    elements = re.search(r'elements: (!\d+)', line)
    if not elements:
        die(f'struct `{struct}` has no elements list')
    for element in tuple_elements(elements.group(1)):
        element_line = node_line(element) or ''
        if re.search(r'!DIDerivedType\(tag: DW_TAG_member, name: "'
                     + re.escape(field) + r'"[,)]', element_line):
            return struct_node, element
    die(f'struct `{struct}` has no member `{field}`')


def find_global(name):
    m = re.search(
        r'^(!\d+) = distinct !DIGlobalVariable\(name: "'
        + re.escape(name) + r'"[,)][^\n]*$',
        text, re.MULTILINE)
    if not m:
        die(f'no debug info for global `{name}` '
            f'(optimized away? mark it #[used])')
    return m.group(1)


def find_function(name):
    m = re.search(
        r'^(!\d+) = (?:distinct )?!DISubprogram\(name: "'
        + re.escape(name) + r'"[,)][^\n]*$',
        text, re.MULTILINE)
    if not m:
        die(f'no debug info for function `{name}` '
            f'(inlined away? mark it #[inline(never)] #[no_mangle])')
    return m.group(1)


def find_argument(function, index):
    subprogram = find_function(function)
    line = node_line(subprogram)
    retained = re.search(r'retainedNodes: (!\d+)', line)
    if not retained:
        die(f'function `{function}` retains no parameter debug info')
    for element in tuple_elements(retained.group(1)):
        element_line = node_line(element) or ''
        if re.search(r'!DILocalVariable\(.*\barg: ' + str(index + 1) + r'[,)]',
                     element_line):
            return element
    die(f'function `{function}` has no parameter at index {index}')


# --------------------------------------------------------------- type tags --

def tag_pointer_type(struct, field, member, tags):
    """Point a member at a private, tagged copy of its pointer type.

    The pointer DIDerivedType rustc emitted is uniqued and shared with every
    other `*mut T` in the module, so annotating it in place would tag all of
    them. Cloning it under a distinguishing name keeps the tag local. BTF drops
    the names of PTR/CONST/VOLATILE/RESTRICT types, so the name never escapes.
    """
    member_line = node_line(member)
    base = re.search(r'baseType: (!\d+)', member_line)
    if not base:
        die(f'`{struct}.{field}` has no base type')
    base_line = node_line(base.group(1)) or ''
    if 'DW_TAG_pointer_type' not in base_line:
        die(f'`{struct}.{field}` is not a pointer; btf_type_tag needs one')

    unique = f'{struct}__{field}__btf_type_tag'
    clone = re.sub(r'^!\d+ = ', '', base_line)
    if 'name: "' in clone:
        clone = re.sub(r'name: "(?:[^"\\]|\\.)*"', f'name: "{unique}"', clone, count=1)
    else:
        clone = clone.replace('DW_TAG_pointer_type,',
                              f'DW_TAG_pointer_type, name: "{unique}",', 1)
    clone = f'{clone[:-1]}, annotations: {annotations_node(tags)})'

    node = alloc()
    new_metadata.append(f'{node} = {clone}')
    replace_node_line(member, member_line.replace(
        f'baseType: {base.group(1)}', f'baseType: {node}', 1))


# ----------------------------------------------------------------- dispatch --

# Group by target so a member that gets both a type tag and a decl tag, or two
# decl tags, produces one annotations tuple per node rather than several.
targets = {}
for kind, name, extra, tag_kind, tag in directives:
    targets.setdefault((kind, name, extra, tag_kind), []).append((tag_kind, tag))

for (kind, name, extra, tag_kind), tags in targets.items():
    if kind == 'm':
        member_target = find_member(name, extra)
        if tag_kind == 't':
            tag_pointer_type(name, extra, member_target[1], tags)
        else:
            attach_annotations(member_target[1], tags, f'`{name}.{extra}`')
    elif kind == 's':
        attach_annotations(find_struct(name), tags, f'struct `{name}`')
    elif kind == 'g':
        attach_annotations(find_global(name), tags, f'global `{name}`')
    elif kind == 'f':
        attach_annotations(find_function(name), tags, f'function `{name}`')
    elif kind == 'a':
        attach_annotations(find_argument(name, int(extra)), tags,
                           f'`{name}` parameter {extra}')
    else:
        die(f'unknown directive kind `{kind}`')

# ------------------------------------------------------ drop the manifest --
#
# BTFDebug walks the module's globals, so removing the definitions is enough to
# keep the manifest out of BTF; the orphaned DIGlobalVariableExpressions left
# behind in the compile unit are never visited.

if manifest_globals:
    dead = set(manifest_globals)
    text = MANIFEST_RE.sub('', text)

    def prune_used(m):
        kept = [e.strip() for e in m.group(3).split(',')
                if e.strip().removeprefix('ptr ') not in dead]
        if not kept:
            return ''
        joined = ', '.join(kept)
        return (f'{m.group(1)} = appending global [{len(kept)} x ptr] '
                f'[{joined}], section "llvm.metadata"')

    text = re.sub(
        r'^(@llvm\.(?:compiler\.)?used) = appending global \[(\d+) x ptr\] '
        r'\[(.*)\], section "llvm\.metadata"$',
        prune_used, text, flags=re.MULTILINE)

if new_metadata:
    text = text.rstrip() + '\n' + '\n'.join(new_metadata) + '\n'

open(sys.argv[2], 'w').write(text)
