#!/usr/bin/env python3
"""
Generate CO-RE accessor shims (core_defs.c) from Rust source files.

Scans .rs files for two things:

1. Kernel struct layouts in specially-formatted comments:

    // @core_struct sched_ext_entity {
    //     dsq_vtime: unsigned long long,
    //     slice: unsigned long long,
    //     weight: unsigned int,
    //     flags: unsigned int,
    // }
    // @core_struct task_struct {
    //     scx: sched_ext_entity,
    //     pid: unsigned int,
    // }

2. core_read!/core_write! macro invocations that name the C shims:

    core_read!(pid -> u32, __core_read_task_struct__pid);
    core_write!(set_scx_slice(u64), __core_write_task_struct__scx__slice);

The naming convention encodes the access chain:
    __core_read_<root_struct>__<field1>__<field2>__...
    __core_write_<root_struct>__<field1>__<field2>__...

Usage: gen_core.py [input.rs ...] -o core_defs.c
"""
import re
import sys
import os

# Collect all .rs files from argv, or default to *.rs in cwd
output = None
rs_files = []
i = 1
while i < len(sys.argv):
    if sys.argv[i] == '-o' and i + 1 < len(sys.argv):
        output = sys.argv[i + 1]
        i += 2
    else:
        rs_files.append(sys.argv[i])
        i += 1

if not rs_files:
    rs_files = sorted(f for f in os.listdir('.') if f.endswith('.rs'))
if not output:
    output = 'core_defs.c'

# --- Parse @core_struct blocks ---
# struct_name -> [(field_name, c_type_string)]
structs = {}

STRUCT_RE = re.compile(
    r'//\s*@core_struct\s+(\w+)\s*\{(.*?)//\s*\}',
    re.DOTALL)
FIELD_RE = re.compile(
    r'//\s+(\w+)\s*:\s*(.+?)\s*,')

for path in rs_files:
    text = open(path).read()
    for m in STRUCT_RE.finditer(text):
        name = m.group(1)
        body = m.group(2)
        fields = []
        for fm in FIELD_RE.finditer(body):
            fields.append((fm.group(1), fm.group(2)))
        if fields:
            existing = structs.get(name, [])
            existing_names = {f[0] for f in existing}
            for f in fields:
                if f[0] not in existing_names:
                    existing.append(f)
                    existing_names.add(f[0])
            structs[name] = existing

# --- Parse core_read!/core_write! shim names ---
SHIM_RE = re.compile(r'(__core_(?:read|write|ptr)_\w+)')

shims = set()
for path in rs_files:
    text = open(path).read()
    for m in SHIM_RE.finditer(text):
        shims.add(m.group(1))

# --- Resolve access chains ---
# __core_read_task_struct__scx__weight
#   -> operation=read, root=task_struct, chain=[scx, weight]

def parse_shim(name):
    m = re.match(r'__core_(read|write|ptr)_(\w+?)(__\w+)$', name)
    if not m:
        return None
    op = m.group(1)
    rest = m.group(2) + m.group(3)
    # Split on __ but the root struct name may contain _ (e.g. task_struct)
    # Strategy: try to match known struct names as prefix
    for sname in sorted(structs.keys(), key=len, reverse=True):
        if rest.startswith(sname + '__'):
            chain = rest[len(sname) + 2:].split('__')
            return op, sname, chain
    return None

# --- Resolve C return type by walking the chain ---

def resolve_chain_type(root, chain):
    """Walk the field chain and return the C type of the final field."""
    cur_struct = root
    for i, field in enumerate(chain):
        if cur_struct not in structs:
            return None
        for fname, ftype in structs[cur_struct]:
            if fname == field:
                if i == len(chain) - 1:
                    return ftype
                # intermediate: ftype should be another struct name
                cur_struct = ftype.strip()
                break
        else:
            return None
    return None

# --- Generate C ---

lines = []
lines.append('// SPDX-License-Identifier: GPL-2.0')
lines.append('// Auto-generated by gen_core.py — do not edit.')
lines.append('//')
lines.append('// CO-RE accessor shims for kernel types used by Rust BPF programs.')
lines.append('')

# Emit struct definitions (order: dependencies first)
emitted = set()

def emit_struct(name):
    if name in emitted or name not in structs:
        return
    # Emit dependencies first
    for _, ftype in structs[name]:
        dep = ftype.strip()
        if dep in structs:
            emit_struct(dep)
    emitted.add(name)
    lines.append(f'struct {name} {{')
    for fname, ftype in structs[name]:
        if ftype in structs:
            lines.append(f'\tstruct {ftype} {fname};')
        else:
            lines.append(f'\t{ftype} {fname};')
    lines.append(f'}} __attribute__((preserve_access_index));')
    lines.append('')

for sname in structs:
    emit_struct(sname)

# Emit accessor functions
for shim_name in sorted(shims):
    parsed = parse_shim(shim_name)
    if not parsed:
        print(f'warning: cannot parse shim name: {shim_name}', file=sys.stderr)
        continue
    op, root, chain = parsed
    c_type = resolve_chain_type(root, chain)
    if not c_type:
        print(f'warning: cannot resolve type for {shim_name} '
              f'(root={root}, chain={chain})', file=sys.stderr)
        continue

    access = 'p->' + '.'.join(chain)
    is_struct_type = c_type in structs

    if op == 'read':
        if is_struct_type:
            lines.append(f'struct {c_type} *{shim_name}(struct {root} *p)')
        else:
            lines.append(f'{c_type} {shim_name}(struct {root} *p)')
        lines.append('{')
        if is_struct_type:
            lines.append(f'\treturn &{access};')
        else:
            lines.append(f'\treturn {access};')
        lines.append('}')
    elif op == 'write':
        lines.append(f'void {shim_name}(struct {root} *p, {c_type} v)')
        lines.append('{')
        lines.append(f'\t{access} = v;')
        lines.append('}')
    elif op == 'ptr':
        if is_struct_type:
            lines.append(f'struct {c_type} *{shim_name}(struct {root} *p)')
        else:
            lines.append(f'{c_type} *{shim_name}(struct {root} *p)')
        lines.append('{')
        lines.append(f'\treturn &{access};')
        lines.append('}')
    lines.append('')

with open(output, 'w') as f:
    f.write('\n'.join(lines))

n_structs = len(emitted)
n_shims = sum(1 for s in shims if parse_shim(s))
print(f'gen_core: {n_structs} structs, {n_shims} shims -> {output}')
